TILE_ = "TILE"
GBUF_ = "GBUF"
ROUTER_ = "ROUTER"
EXT_MEM_ = "EXT_MEM"
PE_ = "PE"
NOC_ = "NOC"
NOP_ = "NOP"
SRAM_ = "SRAM"

MAC_VECTOR_ = "MAC_VECTOR"
IA_BUFFER_ = "IA_BUFFER"
W_BUFFER_ = "W_BUFFER"
ACC_BUFFER_="ACC_BUFFER"

MULTICAST_ = "MULTICAST"
UNICAST_ = "UNICAST"

LOAD_ = "LOAD"
STORE_ = "STORE"

PE_O_ = "PE_O"
PE_N_ = "PE_N"
PE_R_ = "PE_R"
PE_C_ = "PE_C"
PE_H_ = "PE_H"
PE_W_ = "PE_W"
PE_S_ = "S"
PE_K_ = "K"

TILE_H_ = "TILE_H"
TILE_W_ = "TILE_W"
TILE_N_ = "TILE_N"
TILE_O_ = "TILE_O"
TILE_K_ = "TILE_K"


IA_BYTES_TO_LOAD_ = "IA_BYTES_TO_LOAD"
W_BYTES_TO_LOAD_ = "W_BYTES_TO_LOAD"

# NOC packet type
MEM_READ_REQ_ = "MEM_READ_REQ"
MEM_WRITE_REQ_ = "MEM_READ_REQ"
EXT_MEM_DATA_ = "EXT_MEM_DATA"

CACHE_LINE_BYTES_ = 64

LAYER_TYPE_ = "LAYER_TYPE"
FC_ = "FC"
CONV_ = "CONV"